### ISSUE TITLE
estimate-phase-beagle can't open CYP2D6.vcf.gz

### ISSUE THREAD

**Issue by NaphatCode** [sbslee/pypgx#106]
First of all, I would like to state that PyPGx is such a very powerful, user-friendly star allele caller.
I am using PyPGx to genotype my VCF file via Docker container quay.io/biocontainers/pypgx:0.21.0--pyh7cba7a3_0 (I have tried installing through conda but I ran into library error.)

My data is _CYP2D6_ targeted sequencing from Nanopore. 

`pypgx run-long-read-pipeline ` can run successfully with WhatsHap phasing. 
The problem is when I want to compare Whatshap with Beagle in PyPGx, `pypgx estimate-phase-beagle `can't open CYP2D6.vcf.gz in its own database.

pypgx import-variants can run successfully as followed
```
`pypgx import-variants CYP2D6 myvcf.vcf.gz imported-variants` 
Saved VcfFrame[Imported] to: imported-variants
```

However, pypgx estimate-phase-beagle show these following errors
```
[E::hts_open_format] Failed to open file "/root/pypgx-bundle/1kgp/GRCh37/CYP2D6.vcf.gz" : No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/pypgx", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/pypgx/__main__.py", line 33, in main
    commands[args.command].main(args)
  File "/usr/local/lib/python3.10/site-packages/pypgx/cli/estimate_phase_beagle.py", line 54, in main
    result = utils.estimate_phase_beagle(
  File "/usr/local/lib/python3.10/site-packages/pypgx/api/utils.py", line 825, in estimate_phase_beagle
    has_chr_prefix = pyvcf.has_chr_prefix(panel)
  File "/usr/local/lib/python3.10/site-packages/fuc/api/pyvcf.py", line 779, in has_chr_prefix
    vcf = VariantFile(file)
  File "pysam/libcbcf.pyx", line 4117, in pysam.libcbcf.VariantFile.__init__
  File "pysam/libcbcf.pyx", line 4342, in pysam.libcbcf.VariantFile.open
FileNotFoundError: [Errno 2] could not open variant file `b'/root/pypgx-bundle/1kgp/GRCh37/CYP2D6.vcf.gz'`: No such file or directory
```

What could possibly be the cause and solution of this problem?

**Comment by sbslee** [comment]
@NaphatCode,

Thank you for the kind words. The problem was caused because you haven't downloaded the resource bundle for PyPGx. For details, please see the [Resource bundle](https://pypgx.readthedocs.io/en/latest/readme.html#resource-bundle) section:

```
$ cd ~
$ git clone --branch 0.21.0 --depth 1 https://github.com/sbslee/pypgx-bundle
```

BTW, please also note that I'm not sure who is uploading PyPGx as a Docker container, but I strongly recommend that you download PyPGx via conda. If you encounter an issue, please post an issue about it here and I will try to help you solve the issue -- I can't guarantee the performance of PyPGx versions installed via Docker.
