### ISSUE TITLE
Issue with running a large sample dataset in pypgx 

### ISSUE THREAD

**Issue by sumudu-rangika** [sbslee/pypgx#108]
Hi Steven,

I have a WGS dataset with >100,000 samples. I used an initial set of 10,000 samples with an extracted VCF region for CYP2C9 to as a test run. Below is the command I used in PyPgx v0.19.0 

pypgx run-ngs-pipeline \
CYP2C9 \
grch38-CYP2C9-pipeline \
--variants extracted_10k_cyp2c9.vcf.gz \
--do-not-plot-copy-number \
--do-not-plot-allele-fraction \
--assembly GRCh38

I have run this on our HPC with ncpus=8, mem=60GB. But I couldn't find a way to increase the memory that the tool use. It has been almost 20hrs and this is still running. 

Is there any way that I can speed up this process? At least to parallelized the run with 40,000 samples per gene.

Thank you in advance !
Best
Sumudu

**Comment by sbslee** [comment]
@sumudu-rangika,

My apology for the delayed response, I just came back from my honeymoon :)

40,000 samples, whooa! I had once run into a similar issue when I had to apply PyPGx (previously Stargazer) to >50,000 samples for single gene (CYP2D6). See this Nature [paper](https://www.nature.com/articles/s41586-021-03205-y) if you're interested.

But basically, what I recommend is parallel computing as you suggested. By design, the PyPGx pipeline is not meant to process that many samples at once. In my experience, a batch size of 200~500 works great.

Please let me know if you have any further questions.
