### ISSUE TITLE
Issue with pypgx.get_recommendation

### ISSUE THREAD

**Issue by marcelthieljit** [sbslee/pypgx#114]
Hi!

It looks like I found error when working with pypgx.get_recommendation from the API. According to the documentation, the output of the following

>  pypgx.get_recommendation('codeine', 'CYP2D6', 'Normal Metabolizer')

 should be:

>  'Use codeine label recommended age- or weight-specific dosing.'

Unfortunately, as a result I've got:

> TypeError                                 Traceback (most recent call last)
> <ipython-input-54-9f9bf2662527> in <module>
> ----> 1 pypgx.get_recommendation('codeine', 'CYP2D6', 'Normal Metabolizer')
> 
> ~/.local/lib/python3.8/site-packages/pypgx/api/core.py in get_recommendation(drug, gene1, phenotype1, gene2, phenotype2)
>     640 
>     641     if gene2 is None:
> --> 642         message = (f"Recommendations for {drug} are determined by multiple genes "
>     643                    f"({', '.join(target_genes)}); for best results, specify phenotype for each gene")
>     644         warnings.warn(message)
> 
> TypeError: sequence item 0: expected str instance, float found

**Comment by sbslee** [comment]
@marcelthieljit,

Thanks for reporting the bug. This issue occurred because starting `pandas` version 2.0, the `pandas.read_csv` method treats the `'None'` string as missing value (e.g. `NaN`) and in the `recommendation-table.csv` file I was using `'None'` as string. I made an update in the `0.22.0-dev` branch so that the `'None'` string is not converted to missing value.

Thanks again for the issue.

P.S. Alternatively, you could lower your `pandas` version to `1.x`.
