### ISSUE TITLE
Most recent stargazer package

### ISSUE THREAD

**Issue by ghost** [sbslee/pypgx#12]
Hi, thanks for this package.

I am currently trying to properly install stargazer to use with this package. I noticed [here](https://github.com/sbslee/pypgx/blob/master/pypgx/bam2gt.py#L96) that the command to run stargazer is different from the package that I have. Where do I get the most up to date stargazer distro?

**Comment by sbslee** [comment]
Hi @jamesvanalstine,

Thanks for reaching out, and you are absolutely right to be confused there. There is a long discussion to be had as for why this all happened, but the bottom line is:

1. You can get the latest Stargazer version (v1.0.8) from the official website: https://stargazer.gs.washington.edu/stargazerweb/
2. To get help on how to run this version, run: `python3 path/to/Stargazer_v1.0.8/stargazer.py genotype -h`
3. If you go to the official website, you will notice that Stargazer has many, what I call, auxiliary tools (e.g. `pipeline`) -- all of these will be removed in the next version (v1.0.9) and that's what `pypgx` is for
4. For now, you shouldn't use PyPGx tools that run Stargazer (e.g. `bam2gt`) because they are assuming you have access to a particular version of Stargazer that is not supported anymore -- instead, use PyPGx to create the input files for Stargazer_v1.0.8, i.e. VCF and GDF files, with `bam2gdf` and `bam2vcf2`.

I'm sorry for the inconvenience (I'm aware the PyPGx doc is outdated in this regard). I am in the process of clarifying it. Please let me know if you have additional questions.
