### ISSUE TITLE
Using CRAM in stead of BAM files 

### ISSUE THREAD

**Issue by ebernsen** [sbslee/pypgx#132]
Hi! 

We want to use CRAM files of whole genome sequencing data. We tested using a CRAM file, but it didn't work for PyPGx. 
As we want to use PyPGx for many samples, converting CRAM to BAM is not an option. 

Is it possible to adapt the tool to use CRAM files as well?

Best, 
Emma

**Comment by sbslee** [comment]
@ebernsen,

I haven't personally tested PyPGx with CRAM, but I'm surprised to hear that it didn't work. Most of the methods in PyPGx are based on samtools, which works natively with both BAM and CRAM. Could you please tell me exactly what you did to conclude that PyPGx doesn't work with CRAM? Providing your exact CLI commands and the error messages would be a good start. Additionally, could you please share one of your CRAM files so that I can reproduce the issue (sbstevenlee@gmail.com)?

**Comment by ebernsen** [comment]
hi! 
We followed the following steps (see attached) 
![image](https://github.com/sbslee/pypgx/assets/78735382/dd018906-502f-451c-aeb8-cbc243d51050)

Step 2: `singularity exec --bind /hpc/cram_files:/input --bind /hpc/pypgx/:/output --writable-tmpfs  /hpc/pypgx/pypgx.sif pypgx create-input-vcf --assembly GRCh38 /output/000HUQ_WGS.vcf.gz /input/Homo_sapiens_assembly38.fasta /input/000HUQ_WGS.cram`

Error: 
```
[E::bgzf_flush] File write failed (wrong size)
/usr/local/bin/python: /tmp/tmpbtvuwvti/likelihoods.ubcf: Unknown error 974942368
```


I am afraid we cannot share the CRAM file as this contains patient info.

**Comment by ebernsen** [comment]
We are going to run the tool with an example CRAM and will provide that one to you (if it works :) ).

**Comment by ebernsen** [comment]
We tested this example CRAM: https://www.ebi.ac.uk/ena/browser/view/ERZ254925 and that gave the same error as the one we are using that contains patient data

**Comment by sbslee** [comment]
Hi @ebernsen,

Thanks for your patience. I have empirically confirmed that PyPGx natively supports CRAM files as input. I have added a section on the tutorial page in the `0.26.0-dev` branch to reflect this. Please see this [page](https://pypgx.readthedocs.io/en/0.26.0-dev/tutorials.html#genotyping-with-cram-files) for details.

I could not test the linked CRAM file because I don't have access to the FASTA file that was used to generate the CRAM file. In your case, are you sure the `/input/Homo_sapiens_assembly38.fasta` file is exactly the one used to create `/input/000HUQ_WGS.cram`?

Also, what's the sequencing platform used to create your CRAM files (e.g., Illumina NovaSeq 6000)?

**Comment by sbslee** [comment]
Closed due to inactivity. Please feel free to re-open it if necessary.
