### ISSUE TITLE
How PyPGx deal with missing data

### ISSUE THREAD

**Issue by xjq8065524** [sbslee/pypgx#142]
Hi,

I'm wondering if there's any documentation on how PyPGx handles missing values in the input pVCF file. Specifically:

(1) What happens if an SNV position required for PGx calling is missing for all samples?

(2) How does PyPGx handle cases where the genotype for a PGx position is missing for a few samples and denoted as "." in the pVCF file? It appears that PyPGx stops running when it encounters a ".". Is there a way to ignore this and continue processing the remaining samples with complete genotypes?

(3) Can i get the comprehensive list of SNV positions that PyPGx uses for calling these >80 pharmacogenes?

**Comment by sbslee** [comment]
@xjq8065524,

Great questions!

(1) It depends on what you mean by "missing." If you are talking about a multi-sample VCF from WGS and certain loci are missing from that VCF, it means those loci are homozygous reference and therefore they will be treated as such by PyPGx. If you are talking about a multi-sample VCF from SNP array and certain loci are missing from that VCF, it means that those loci were never investigated (i.e., genotyped) and therefore they will be falsely treated as homozygous reference even though there might be variants. That's why for the latter case, you may consider performing imputation to obtain variant information for ungenotyped markers.

(2) Not sure what you mean by "pVCF" (do you mean "gVCF?"), but could you share the exact command line you used, the version of PyPGx, the exact output of PyPGx including the error message? Generally speaking, genotype calls with missing information (i.e., `./.`) should be tolerable by PyPGx, but I need to have more information to give you helpful feedback.

(3) Sure. See the [allele-table.csv](https://github.com/sbslee/pypgx/blob/master/pypgx/api/data/allele-table.csv).

**Comment by xjq8065524** [comment]
Thanks Steven. All clear for points 1 and 3.

Re 2, I think the multi-sample VCF is largely equivalent to the pVCF (population-based VCF) I mentioned earlier, apart from additional information provided in the `INFO` field/column and typically represents a large dataset used in Biobanks.

So, in my multi-sample VCF from WGS, I have checked that some samples have missing genotypes (no genotype call, probably due to low coverage at certain positions?) and are shown as: "0/.", "./0", "./." or " . " etc.

I used the following command:
pypgx run-ngs-pipeline \
> CYP3A5 \
> spark-CYP3A5-pipeline \
> --variants spark_CYP3A5_extracted_first200_samples_norm_GT_9.vcf.gz \
> --assembly GRCh38

The resulting error message was:
Exception in thread "main" java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Sample XXX has an inconsistent number of alleles. The first genotype is diploid, but the genotype at position chr7:99646782 is haploid

![image](https://github.com/user-attachments/assets/23d7bbdc-012b-4a2c-beac-bc571e9d320d)

**Comment by sbslee** [comment]
@xjq8065524,

Thank you for providing the information. The error message is returned by Beagle, not PyPGx, and indicates that the sample has a haploid missing call (i.e., `.`) for an autosomal chromosome. You need to convert these haploid missing calls to diploid missing calls (i.e., `./.`).

**Comment by xjq8065524** [comment]
Thanks a lot, the problem has been solved.
