### ISSUE TITLE
Recommendations and contig error when starting from vcf

### ISSUE THREAD

**Issue by evyamor** [sbslee/pypgx#144]
I have a few questions regarding the recommendation table, as well as an issue I encountered related to VCF processing. I would appreciate your insights on the following points:

Recommendation Table:
  Gene-Pair Recommendations: I noticed that the recommendations in the table are based on up to two genes. Is it appropriate to apply the same recommendation for a drug based on just one gene and phenotype, without taking the second gene into consideration when both genes are mentioned? This seems particularly relevant in cases where recommendations are listed only for specific gene pairs in the table.
  
  Inclusion of All Recommendations: Does the recommendation table capture all possible recommendations generated by pypgx, or are there additional recommendations potentially generated by the code that might not appear in the table?
  
  CPIC Guidelines Version: Could you please confirm the date of the CPIC guidelines to which the recommendation table has been updated? It would be helpful to know the reference version for the recommendations.

VCF Contig Error:
When processing a VCF file (not generated by pypgx from BAM), I encountered the following error repeatedly: ValueError: contig 1/2/3...
After some investigation, I found that sorting and reindexing the VCF file resolved the issue.

Thank you for your time and assistance. I look forward to your feedback on these points.

Best regards,
Evyatar Mor

**Comment by sbslee** [comment]
Hi @evyamor,

These are great questions!

1. Recommendation Table

> Gene-Pair Recommendations: I noticed that the recommendations in the table are based on up to two genes. Is it appropriate to apply the same recommendation for a drug based on just one gene and phenotype, without taking the second gene into consideration when both genes are mentioned? This seems particularly relevant in cases where recommendations are listed only for specific gene pairs in the table.

If a certain drug is known to be metabolized by two genes but you only have a genotype for one of the two genes, it's not ideal but you can still provide a useful recommendation based on the genotype data. In such cases, PyPGx outputs a warning to signify the user that the target drug is metabolized by more than one gene.

```
# Some recommendations are determined by multiple genes (the order doesn't matter)
pypgx.get_recommendation('fluvastatin', 'CYP2C9', 'Normal Metabolizer')
/Users/sbslee/Desktop/pypgx/pypgx/api/core.py:633: UserWarning: Recommendations for fluvastatin are determined by multiple genes (CYP2C9, SLCO1B1); for best results, specify phenotype for each gene
  warnings.warn(message)
'Prescribe desired starting dose and adjust doses of fluvastatin based on disease-specific guidelines.'
pypgx.get_recommendation('fluvastatin', 'SLCO1B1', 'Normal Function')
/Users/sbslee/Desktop/pypgx/pypgx/api/core.py:633: UserWarning: Recommendations for fluvastatin are determined by multiple genes (CYP2C9, SLCO1B1); for best results, specify phenotype for each gene
  warnings.warn(message)
'Prescribe desired starting dose and adjust doses of fluvastatin based on disease-specific guidelines.'
pypgx.get_recommendation('fluvastatin', 'CYP2C9', 'Normal Metabolizer', 'SLCO1B1', 'Normal Function')
'Prescribe desired starting dose and adjust doses of fluvastatin based on disease-specific guidelines.'
pypgx.get_recommendation('fluvastatin', 'SLCO1B1', 'Normal Function', 'CYP2C9', 'Normal Metabolizer')
'Prescribe desired starting dose and adjust doses of fluvastatin based on disease-specific guidelines.'
```

You can see more examples from the method's [documentation](https://pypgx.readthedocs.io/en/latest/api.html#pypgx.api.core.get_recommendation).

2. Inclusion of All Recommendations

> Does the recommendation table capture all possible recommendations generated by pypgx, or are there additional recommendations potentially generated by the code that might not appear in the table?

The recommendation table itself captures all possible options.

3. CPIC Guidelines Version

> Could you please confirm the date of the CPIC guidelines to which the recommendation table has been updated? It would be helpful to know the reference version for the recommendations.

This is rather difficult because the field of PGx changes too rapidly, and it's impossible for PyPGx to sync up with different databases every time there is a new version update. I try my best but so far this has been mostly one man's efforts, so what you see in the [CHANGELOG](https://pypgx.readthedocs.io/en/latest/changelog.html) section is what you get.

4. VCF Contig Error

> When processing a VCF file (not generated by pypgx from BAM), I encountered the following error repeatedly: ValueError: contig 1/2/3...
After some investigation, I found that sorting and reindexing the VCF file resolved the issue.

Thanks for sharing the tip! Let me know if you encounter any other issues.

**Comment by sbslee** [comment]
Closed due to inactivity. Please feel free to re-open it if necessary.
