### ISSUE TITLE
pypgx on anaconda

### ISSUE THREAD

**Issue by kokyriakidis** [sbslee/pypgx#21]
Hi!

It seems that pypgx is missing from Anaconda and cannot install it. Have you noticed it?

**Comment by sbslee** [comment]
Hi @kokyriakidis,

Thanks for your continued interest in PyPGx. I took it down from Anaconda because 1) it was not being downloaded actively and 2) I'm completely re-writing the package. I didn't want people to get confused between previous versions and the new version. The new version -- which is currently being developed under the `0.4.0-dev` branch -- will be re-uploaded to PyPI and Anaconda as soon as it's released. Also, the previous version was uploaded in Anaconda via my personal channel (`sbslee`) but starting the new version, PyPGx will be depsoited via the `bioconda` channel. Hope this answers your question.
