### ISSUE TITLE
Future Plans

### ISSUE THREAD

**Issue by kokyriakidis** [sbslee/pypgx#22]
Hi @sbslee !

I am currently working on a new PGx pipeline and wanted to incorporate pypgx into it. I saw your developing branch and wondered if pypgx will support genotyping. Will it have the same functionality as Stargazer?

**Comment by sbslee** [comment]
Hey, I'm glad you are considering to incorporate PyPGx into your pipeline. The short answer is yes, the new version will support genotyping as well. But my main vision for the new PyPGx is to provide a unified "platform" for PGx research instead of it being just another genotyping program like Stargazer. For example, when I was developing Stargazer, I wanted to explore many different ways of detecting structural variation, but it was difficult because everything was kind of "locked in". But with PyPGx I am able to create and deploy various algorithms for detecting structural variation; in fact, I already built a support vector machine-based CNV caller. In any case, if things go well I hope other people would jump into PyPGx and build their own genotyping tool, etc. Hope this answers your question.

**Comment by kokyriakidis** [comment]
The big problem about Stargazer is that users have to do several steps to download the tool and developers cannot incorporate it directly to their pipelines due to the non-conda or docker/singularity image. I am currently developing a best-practice pipeline that can handle Illumina WGS, Nanopore and PACBIO reads, performing optimal qc, optimal mapping, optimal variant calling etc. It would be great to have pypgx genotype PGx genes using the vcf I provide and then parse pypgx results and feed them into PharmCAT as outside calls (using only their report functionality and ignoring their genotyping which lack sv and cnv functionality). 

So I will wait for the next release of pypgx and we could talk about it if you are interested!

Good job :)

**Comment by sbslee** [comment]
Your project sounds exciting! Yea, stay tuned for the official release of PyPGx :)
