### ISSUE TITLE
Could not load index for bam list having for more than 1018 lines

### ISSUE THREAD

**Issue by NTNguyen13** [sbslee/pypgx#30]
Hi, I'm trying those 2 functions to calculate control and sample depth of coverage:

```
bamlist=$1
out_dir=$2

control_gene='VDR'

pypgx compute-control-statistics \
    $out_dir/control-statistcs-${control_gene}.zip \
    --gene VDR \
    --fn $bamlist \
    --assembly GRCh38    

pypgx prepare-depth-of-coverage \
    $out_dir/depth-of-coverage.zip \
    --fn $bamlist \
    --assembly GRCh38
```

I successfully experimented it on bamlist with around 250 samples, but when I tried it with a list of 1050 samples, it fails and shows this message:

`pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=samtools depth: cannot load index for "file.bam"\n'`

I tried shuffling the sample list, and it always fails at sample 1018th, no matter what file at that position. I'm using Whole Genome Sequencing files.

Could you please help me with this? I'm using branch 0.90-dev.

Thank you very much

**Comment by sbslee** [comment]
@NTNguyen13, that is one weird issue that I have not seen before. The mere fact that a subset of 250 samples is working properly tells me that it's a `pysam` error rather than a `pypgx` error... That being said, I would recommend you to break up your sample set into groups of 200~250 samples anyways, because otherwise it's going to take a very long time to haplotype phase your SNVs and indels if you are going to perform genotype analysis with PyPGx.

**Comment by NTNguyen13** [comment]
Hi, it worked well for my case, I will close the issue.
