### ISSUE TITLE
Regarding multiple alleles on the same strand

### ISSUE THREAD

**Issue by NTNguyen13** [sbslee/pypgx#35]
Hi, I found that in our population data, sometimes there are multiple alleles detected on the same strand of one individual. This will affect 2 things:

1. How should we represent that PGx gene?
2. How should we assign the activity score for that case?

This issue made me scratching my head for a few days, then I talked to some experts and came across this paper: https://ascpt.onlinelibrary.wiley.com/doi/full/10.1002/cpt.2122

So I get the general idea:

1. If the variants from those alleles are not overlapping each other, we can represent them by the + notation. If they are overlap, we can represent 1 allele + the additional variants from the other allele.
2. We can choose the more 'severe' score among 2 or more alleles.

However, this raises other concerns as well, especially about complex CNV. As I am working with PyPGx, I propose my below ideas to enhance it, please correct me if my idea is not appropriate
![SimplerGenotyper drawio](https://user-images.githubusercontent.com/39985901/145454599-ffdc8c29-b966-436d-8a89-d093ff83f840.png)

At this moment, we just deal with the PGx gene without CNV first. As PyPGx currently reports all detected allele in `Haplotype` columns, it's already easier to report multiple alleles but I will add one more columns in `allele-table.tsv` to indicate which variants are overlapping each other.

In the later `call phenotype` step, because our alleles is already sorted to prioritize severe allele, I can just use the first instance of `.split('+')` as input for ``call phenotype` function.

Please comment if my idea aligns with PyPGx development direction.

**Comment by sbslee** [comment]
@NTNguyen13,

Thanks for this very detailed discussion! First of all, I want to clarify one thing. When you wrote:

> multiple alleles detected on the same strand

Do you mean multiple alleles detected on the same *chromosome*? If this's what you mean, I get what you are saying. If you really meant "strand" here, then please elaborate.

Assuming you are talking about a scenario where multiple star alleles are detected in a given chromosome (haplotype), this issue is not new, at least not to me. And as you rightly point out, that's exactly why `SampleTable[Results]` has the two columns `Haplotype1` and `Haplotype2` -- i.e. to list candidate star alleles for each haplotype.

Additionally, PyPGx goes one step further by automatically collapsing redundant star alleles (i.e. overlapping star alleles) from the list for each haplotype. Let me give you a concrete example: Assume an individual has one CYP2D6 haplotype with two SNVs 22-42525772-G-A and 22-42526694-G-A. This haplotype can produce two candidate star alleles *17 (22-42525772-G-A) and *64 (22-42525772-G-A, 22-42526694-G-A). In this case, because *17 is redundant in the sense that it's complexly overlapping with *64 (but not the other way around), PyPGx will remove *17 from the list, only reporting *64 (this process is termed "collapsing"). If you are interested, you can look at the code [here](https://github.com/sbslee/pypgx/blob/ad4dda032b555fbede9fc54a41d104b249f4f854/pypgx/api/utils.py#L874).

The tricky situation is when there are multiple non-overlapping star alleles for a given haplotype. In this case, PyPGx will sort candidate alleles using their functional significance (and other factors; see the `pypgx.sort_alleles` method for details), giving priority to alleles with more severe consequence (e.g. poor function > normal function). In the final report, PyPGx will use the most important allele from each haplotype to form a diplotype.

That being said, if I understood you correctly, you want to report all of the candidate star alleles in the final diplotype by representing those in a combined form with `+`, instead of reporting only one star allele per haplotype. I totally get the motivation behind it, and trust me when I say this because I too have thought about this issue for a long time :) **But I came to the conclusion that this's not the way to go because then you are essentially defining a new star allele on the fly.**

For example, let's say an individual has the following CYP2D6 haplotypes: `*1;` and `*4;*10;*74;*2;`. The current version of PyPGx will report `*1/*4` as final diplotype. But if you do `*1/*4+*10+*74+*2`, then you are essentially creating a novel haplotype that does not exist in any of the PGx databases (e.g. PharmVar). Plus, depending on which gene you are talking about, the `+` sign can have a special meaning. For instance, in CYP2D6 it means gene duplication. So when you say `*4+*10` this does NOT translate to having SNVs of both *4 and *10 in one haplotype, but rather it translates to having two copies of CYP2D6, *4 and *10. In UGT1A1, the `+` sign is used exactly as how you are using it. For example, you have three star alleles defined in the following way:

```
*28	Decreased Function	2-234668879-C-CAT
*80	Unknown Function	2-234668570-C-T
*80+*28	Decreased Function	2-234668570-C-T,2-234668879-C-CAT
```

In this case, it's OK to use `*80+*28` because it is actually a defined star allele in CPIC. So the bottom line is, when we encounter a haplotype that can fit multiple star alleles, I believe PyPGx should report all the candidate star alleles in a concise way (i.e. by collapsing redundant alleles), but it shouldn't try to create a novel allele by arbitrarily combining those candidate alleles. This way, I think the interpretation of results is easier.

PS 1. When PyPGx outputs predicted phenotype, it is already based on the enzymatic function of the most severe allele for each haplotype. 

PS 2. Not all genes use the activity score. In fact, many genes use direct diplotype-phenotype mapping from CPIC. Please read the [Phenotype prediction](https://pypgx.readthedocs.io/en/latest/readme.html#phenotype-prediction) page for details.

**Comment by NTNguyen13** [comment]
very interesting! I really admire how you already planned ahead for all of this situations.

I'm planning to add other functional impact of some other genes, such as: CACNA1S, RYR1, CFTR, CYP4F2, G6PD, IFNL3. I see the phenotype prediction page, as well as the categories in `PhenotypeMethod` of gene-table.tsv. I want to add this case to our discussion as well:

- CFTR: https://www.pharmgkb.org/chemical/PA165950341/guidelineAnnotation/PA166114461
In this guideline, the order of clinical action based on on genotyping will be:

G551D Het/Hom > F508del Homozygous > Some other variants Het/Hom. 

However, the meanings of those variant functions have not been defined in the list `FUNCTION_ORDER` yet. Do you think it's OK to add more entry for CFTR variant functionality score?

**Comment by NTNguyen13** [comment]
For case such as CACNA1S and RYR1, I'm planning to add their `PhenotypeMethod` as `Diplotype`, and then add all of the possible combinations of 2 alleles to the `diplotype-table.csv` file (they must be sort using `sort_alleles` method, of course). Finally, I will add their phenotype based on PGKB annotation. Is this OK to do so?

**Comment by sbslee** [comment]
@NTNguyen13, I will close this issue for now because it sounds like we're in the same page. Please reopen it if you want to discuss more about the original topic.

I also moved your new discussion about updating phenotype data for several genes to a new issue (#36). I will respond there.
