### ISSUE TITLE
Help with nanopore data

### ISSUE THREAD

**Issue by Pharmacogenetecist** [sbslee/pypgx#45]
Dear Steven, firstly thank you for such a useful tool!

We have been dabbling in generating nanopore data to evaluate CYP2D6 and hopefully other PGX genes in the future. I was hoping to use the CNV tools as well as some of your graphing tools. I realise I will need a depth of coverage file, and I was wondering how we could go about generating one for our nanopore data? Also, assuming we might be able to use the control-statistics which you provided or generate one from our own files?

Happy to share some vcf and or BAM files if required.

FYI - I have been able to call variants/phenotypes from nanopore data by using the run-chip-pipeline.

**Comment by sbslee** [comment]
Thanks for your interest in PyPGx!

1. I'm currently updating the documentation to make the PyPGx pipelines more transparent (https://pypgx.readthedocs.io/en/0.12.0-dev/readme.html#pipelines). This will be reflected in the upcoming `0.12.0` version (planned to be released in early February). Hopefully, this will give you a better idea of how to generate input files for PyPGx including `CovFrame[DepthOfCoverage]` and `SampleTable[Statistcs]`.
2. Basically, from BAM files you can generate a `CovFrame[DepthOfCoverage]` file using the `prepare-depth-of-coverage` command ([doc](https://pypgx.readthedocs.io/en/latest/cli.html#prepare-depth-of-coverage)) and a  `SampleTable[Statistcs]` file using the `compute-control-statistics` command ([doc](https://pypgx.readthedocs.io/en/latest/cli.html#compute-control-statistics)). So `SampleTable[Statistcs]` is not something PyPGx provides; you need to create one for your own dataset.
3.  I've always been interested in applying long read data to PGx analysis! Are you currently using the `run-chip-pipeline` command because you only have VCF files as PyPGx input? As the name suggests, the command is for SNP array (chip) data, so you shouldn't really use it for long read data :( Did the `run-ngs-pipeline` command fail on your VCF files?
4. I'd be happy to take a look at your nanopore data (both BAM and VCF)! Can you send them to my gmail account (sbstevenlee@gmail.com)? How big are they (file size, target depth of coverage, mean read length, etc.)? Are they whole genome or target sequencing?
5. Depending on the situation, neither `run-chip-pipeline` nor `run-ngs-pipeline` may be suitable for long read data (the latter is primarily for Illumina short read data). Plus, long read data has its own perks that could be extracted for better PGx genotyping (e.g. variants are already phased so haplotype phasing is not required, structural variation can be detected directly instead of relying on depth of coverage-based inference). This means we may need to come up with a new pipeline specifically for long read data. But we'll see!

**Comment by Pharmacogenetecist** [comment]
Thank you for your detailed response.
I will try your suggestions for (2).
For (3) - The pipeline works fine whit chip. When I try run-ngs-pipeline I get an error
pypgx: error: unrecognized arguments: /WORKSPACE/pypgxtest/BC94.phased.vcf.gz
(4) - I will send you some data. We are running targeted sequencing on ~7kb amplicons. I can send you more of the stats in the email.
(5) - Yes we have been using whatshap to help with phasing. Ideally I would like to use your graphing tools to visualize any 2D6 and maybe other CNVs.

**Comment by sbslee** [comment]
The reason you were getting the unrecognized arguments error is because the CLI structures for `run-chip-pipeline` and `run-ngs-pipeline` are different. In the former, a VCF file is a required *positional* argument; you must provide it to run the command. In the latter, a VCF file is an *optional* argument because some genes such as UGT2B17 does not need SNV/indel information -- it only has star alleles defined by CNV. If you look at the [GeT-RM tutorial](https://pypgx.readthedocs.io/en/latest/tutorials.html#genotyping-genes-without-sv), here is an example CLI of genotyping genes only using VCF:

```
$ pypgx run-ngs-pipeline \
CYP3A5 \
grch37-CYP3A5-pipeline \
--variants grch37-variants.vcf.gz
``` 

Please try this again.

When you send me the files, it would be appreciated if you could attach some background and experimental details of the data (e.g. whether the 7 kb amplicon includes both CYP2D6 and CYP2D7).

**Comment by Pharmacogenetecist** [comment]
Thank you, using that worked with nanopore data.

The 7KB amplicon only covers the 2D6 region and minor upstream and downstream portions. I will send you some data tomorrow.

**Comment by sbslee** [comment]
@Pharmacogenetecist,

Thanks for sharing your nanopore data. I was able to download it and do some testing with it. Long story short, I decided that neither `run-ngs-pipeline` nor `run-chip-pipeline` was suit for working with long-read sequencing data. Hence, I created the `run-long-read-pipeline` [command](https://pypgx.readthedocs.io/en/0.13.0-dev/cli.html#run-long-read-pipeline) in the `0.13.0-dev` branch (note that `0.12.0` version was released yesterday). Basically, this command takes advantage of haplotype information from read-backed phasing (i.e. WhatsHap) in input VCF.

At this point, you may wonder why you couldn't continue to use the `run-ngs-pipeline` command since it worked fine for your data before. This is because in `run-ngs-pipeline`, haplotype information in input VCF is wiped out and PyPGx performs statistical phasing to get new haplotype information. This is routinely done with VCF files generated with short Illumina reads, but it's a huge waste of valuable haplotype information for VCF files generated with long-read technique.

If you want to try running `run-long-read-pipeline` yourself, you need to install the `0.13.0-dev` version of `pypgx` and the `0.30.0-dev` version of `fuc`. Below is a step by step guide on how to properly set the environment:

```
mkdir pypgx-long-read
cd pypgx-long-read
conda create -n pypgx-dev pypgx=0.12.0
conda activate pypgx-dev
git clone https://github.com/sbslee/pypgx
cd pypgx
git checkout 0.13.0-dev
pip install -e .
cd ..
git clone https://github.com/sbslee/fuc
cd fuc
git checkout 0.30.0-dev
pip install -e .
cd ~
git clone --branch 0.12.0 --depth 1 https://github.com/sbslee/pypgx-bundle
cd /path/to/pypgx-long-read
pypgx run-long-read-pipeline CYP2D6 CYP2D6-pipeline /path/to/variants.vcf.gz
```

Now that we have a dedicated genotyping pipeline for long-read sequencing data, I'm looking for ways to detect structural variation with it. At the first glance, it appeared none of the six samples with BAM files (BC30, BC42, BC54, BC66, BC78, BC90) had structural variation, but I'll do a more in-depth analysis soon (please let me know if you know for fact any of these samples are supposed to have structural variation). I will let you know when I have updates. In the meantime, let me know if you have any questions/suggestions/comments.

**Comment by Pharmacogenetecist** [comment]
@sbslee Thank you! I will have a go at installing and running the update.
I will also put some known BAM/VCF files of 2D6 samples we know have duplications or deletions into the google shared folder shortly.
