### ISSUE TITLE
Why does `phenotyper` not default to providing phenotypes for drug metabolizing enzymes for UGT1A1, DPYD etc.? 

### ISSUE THREAD

**Issue by brettva** [sbslee/pypgx#5]
Hi @sbslee Steven,

PharmGKB's "diplotype to phenotype" tables for [UGT1A1](https://www.pharmgkb.org/page/ugt1a1RefMaterials), [DPYD](https://www.pharmgkb.org/page/dpydRefMaterials), and other enzymes seem to use phenotype nomenclature consistent with CPIC recommendations [consensus terms](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5253119/pdf/gim201687a.pdf) for drug metabolizing enzymes.

pypgx `phenotyper` seems to default to providing allele functional status for some enzymes. Is there a reason for this?

Example: 
```
from pypgx.phenotyper import phenotyper
phenotyper("tpmt", "*1", "*2")
```

gives `decreased_function`, but based on PharmGKB "diplotype to phenotype", I would have expected something like `Intermediate Metabolizer`

If I wanted phenotypes more comparable with PharmGKB reports, I think realize that I could just change the code in my copy of `phenotyper.py` to output metabolizing phenotypes for these genes, but thought I would get your input before doing so (I'm not a pgx expert).  

On a side note, I wonder if there is an issue with the [webform](https://stargazer.gs.washington.edu/stargazerweb/res/form.html) for downloading the most recent version of stargazer from UW. Unless I am missing something, I have not been able to download using chrome, edge, firefox or brave browsers.

I am a big fan of pypgx and stargazer, thanks for developing. :)

-Brett

**Comment by sbslee** [comment]
Hello Brett @brettva,

Thanks for reporting the issue! First of all, I'm sorry about the download form not working. I contacted the University of Washington team, and they fixed the issue (I checked!). You should now be able to access various Stargazer versions.

In terms of the `phenotyper` method not returning what you would expect, I completely get where you're coming from. First, when it returns results like `decreased_function` as opposed to `poor_metabolizer`, I was just following the standard CPIC guideline set by Caudle et al., 2017 (PMID: 27441996) [Standardizing terms for clinical pharmacogenetic test results: consensus terms from the Clinical Pharmacogenetics Implementation Consortium (CPIC)](https://pubmed.ncbi.nlm.nih.gov/27441996/). Basically, they use allele functional status to also indicate final phenotype of individuals for PGx genes whose phenotype terms have not been defined yet (see the attached screenshot). **Of course, this phenotype represents functional status after combining the two haplotypes.**

![Screen Shot 2020-12-21 at 1 41 26 PM](https://user-images.githubusercontent.com/21111749/102740320-d7382800-4392-11eb-8f10-b25ee174d160.png)

Secondly, for genes like UGT1A1 and DPYD, I do see that they have official phenotype terms (thank you for sending the links!). This is because either they did not exist at the time I wrote PyPGx or I missed them. In either case, this is also precisely the reason I started PyPGx: by making this an open source project, everyone (like you) can catch this kind of issues and fix it together :)

That being said, I am more than happy to fix this on my end, but I also wanted to give you a chance to contribute to PyPGx by making a pull request. Do you want to create a PR so I can review and merge (I promise I will be quick at reviewing your changes)? Otherwise, don't worry at all, I will fix it ASAP. Please let me know.

**Comment by brettva** [comment]
@sbslee I have the changes in my local copy and will put in a PR shortly. Thank you!

**Comment by sbslee** [comment]
@brettva,

Thanks for the PR! FYI, I noticed that the DPYD gene has its own AS-to-phenotype table according to CPIC, so I made some additional changes to reflect this (#8). Hope it makes sense! These changes will be uploaded to pypgx-0.1.35.
