### ISSUE TITLE
Impact of rs2032582A>C variant

### ISSUE THREAD

**Issue by nmtrang00** [sbslee/pypgx#52]
The impact of  rs2032582A>C variant in "pypgx" database is "A893S". However, according to [dbSNP](https://www.ncbi.nlm.nih.gov/snp/rs2032582#hgvs_tab), the impact is "Ser893Ala" or "S893A". Could you please check it again?
Thanks a lot,
Trang

**Comment by sbslee** [comment]
@nmtrang00,

Good question! As you rightly pointed out, rs2032582 is S893A for both GRCh37 and GRCh38. However, the reference (or "wild-type") star allele of the ABCB1 gene, ``ABCB1*1``, has Ala for amino acid position at 893 according to [PharmGKB](https://www.pharmgkb.org/vip/PA166170352):

> ABCB1*1 contains 1236C, 2677G (893Ala), and 3435C.

This means, if you look at the ABCB1 sequence in GRCh37 or GRCh38, you won't find ``ABCB1*1`` -- it's actually ``ABCB1*2`` for both assemblies. This is why if you look at the `gene-table.csv` file, it will say ``*1``, ``*2``, and ``*2`` for the ``RefAllele``,	``GRCh37Default``, and ``GRCh38Default`` columns, respectively.

Always remember, in PGx, genotypes and protein functions are reported compared to the reference star allele (instead of human assembly such as GRCh37 or GRCh38).

**Comment by nmtrang00** [comment]
Hi,
Thanks a lot for your fast reply and clear explanation.
