### ISSUE TITLE
Integration CNV/SV with PyPGx pipeline

### ISSUE THREAD

**Issue by NTNguyen13** [sbslee/pypgx#56]
Hi, as discussed in #32, I want to integrate CNV/SV called by other tools with PyPGx pipeline. Most of the time, those CNV/SV are stored as VCF file, while PyPGx need the CNV/SV to be labelled as in `cnv-table.csv`. In most cases, the label are quite easy to understand, such as DeletionHet, DeletionHom. However, some cases are not as clear, e.g. Tandem2A[CYP2D6], Intron1DeletionA[UGT1A4]. For me, most names with Tandem and A, B, C are quite difficult to understand.
I have some questions:

- How should I understand these above cases? 
- What is the criteria/threshold for labeling a CNV/SV as in `cnv-table.csv`? For example, I have a DEL SV span 1/2 the length of CYP2D6 gene, can I call it Deletion yet?
- In cases I have fully understood the label and criteria, is it OK for me to add CNV as an additional argument to ngs and chip pipeline of PyPGx?

**Comment by sbslee** [comment]
@NTNguyen13,

As always, great questions!

> How should I understand these above cases?

CNV names such as `Tandem2A` from CYP2D6 and `Intron1DeletionA` from UGT1A4 are just labels (or placeholders) that exist purely for convenience -- i.e. for communication purposes. For example, if we wanted to, we could have called them `CYP2D6-SV-4` and `UGT1A4-SV-2`, respectively. However, I wanted to give more informative names than just numbers.

That being said, I think the best way to understand each CNV label is to look at their actual PyPGx output: copy number profile and allele fraction profile. With those we can study each CNV label's copy number status, allele fraction status, and breakpoints. For instance, if you go to [Read the Docs > Genes > CYP2D6 > SV summary for CYP2D6](https://pypgx.readthedocs.io/en/latest/genes.html#cyp2d6), you will find various information and PyPGx outputs for each CNV label. I will show examples for `DeletionHet` below (which corresponds to `CYP2D6*5`).

![Screen Shot 2022-04-19 at 2 40 43 PM](https://user-images.githubusercontent.com/21111749/163927594-6d9ecb98-ff40-43e7-952a-26da80563f60.png)

**Gene Model**

![gene-model-CYP2D6-2](https://user-images.githubusercontent.com/21111749/163926825-c2356c21-d5b8-4b1c-968a-78b4a8250c67.png)

**GRCh37**

![GRCh37-CYP2D6-1](https://user-images.githubusercontent.com/21111749/163926847-4c72442e-e775-4412-af71-70ba5d0bac14.png)

> What is the criteria/threshold for labeling a CNV/SV as in `cnv-table.csv`? For example, I have a DEL SV span 1/2 the length of CYP2D6 gene, can I call it Deletion yet?

Currently, the `cnv-table.csv` file only contains CNV labels that can be detected by the [SVM-based classifier](https://pypgx.readthedocs.io/en/latest/readme.html#structural-variation-detection). That means at least one real NGS sample exists for given CNV. There are no defined inclusion criteria, but I'd first want to see their copy number profile and allele fraction profile for visual inspection at the minimum.

If you have gene deletion that only spans the half of CYP2D6, then I would think it should merit its own CNV label (e.g. `PartialDeletion`) because as you can see above `DeletionHet` means whole gene deletion. However, for whatever reason if that's what you want, i.e. you want to treat partial gene deletion as whole gene deletion, then you could create mapping between CNV calls in your VCF to CNV labels used in PyPGx.

> In cases I have fully understood the label and criteria, is it OK for me to add CNV as an additional argument to ngs and chip pipeline of PyPGx?

As you suggested it, if you want to run `run-ngs-pipeline` with your CNV calls I think the most reasonable approach at this moment is to provide your own PyPGx archive file with the semantic type `SampleTable[CNVCalls]`. You can visit [here](https://pypgx.readthedocs.io/en/latest/readme.html#semantic-types) to see more details on semantic type. I will add a new argument `--cnv-calls` so that when this argument is provided, PyPGx will skip SV detection and simply use whatever is provided by the user.

Let me know what you think.

P.S. As for `run-chip-pipeline`, this command currently does not support SV detection. Did you mean you have a way to detect SV for chip data as well?

**Comment by NTNguyen13** [comment]
Hi, I also speculated that the ML model learned from WGS data, so it will be hard to determine the 'fixed' criteria. I will experiment some more ways to do this, maybe even a ML model on top of the variant to classify them.
I think adding the new argument `--cnv-calls` is great, I'm quite familiar with pypgx semantic now, I can create the file with the right format.
I'm thinking about using CNV Detection tools on microarray, such as PennCNV, with some more false positive filtering and refinement.

**Comment by sbslee** [comment]
> I will experiment some more ways to do this, maybe even a ML model on top of the variant to classify them.
I think adding the new argument `--cnv-calls` is great, I'm quite familiar with pypgx semantic now, I can create the file with the right format.

Then I'd like to postpone the addition of the `--cnv-calls` option until you're finished with experimenting because it's actually a bigger change than I initially expected. Plus, I don't think there will be many people who will end up using this option.

Another idea that came to me is, if you want, consider building a plugin for PyPGx. One of the main goals of PyPGx is to provide a development **platform** for PGx research. That's why it provides extensive API. So if you want to build a genotyping pipeline similar to `run-ngs-pipeline` but the only thing you want to change is how it performs SV detection, then you can easily modify the [`pypgx.api.pipeline.run_ngs_pipeline`](https://pypgx.readthedocs.io/en/latest/api.html#pypgx.api.pipeline.run_ngs_pipeline) code. This way, you don't have to reinvent the wheel and worry about constructing your own star allele database, etc. I would be more than happy to help if you need in this regard. If you are satisfied with the final product, you may be able to even publish your own PGx genotyping package. Or, simply create a new pipeline in PyPGx (e.g. `run-fancy-sv-pipeline`).

```
# Option 1 (a new PyPGx plugin)
$ pypgx your_plugin run-fancy-sv-pipeline ...

# Option 2 (a new PyPGx command)
$ pypgx run-fancy-sv-pipeline ...
```

Just a thought.

> I'm thinking about using CNV Detection tools on microarray, such as PennCNV, with some more false positive filtering and refinement.

Sounds good. Curious to see where that leads us.

**Comment by NTNguyen13** [comment]
Hi, sorry for late reply. I think that create a new PyPGx command sound goods to me. I will make a pull request soon. I would like to close this issue since my question is well-answered.
