### ISSUE TITLE
Segmentation fault when calling create_input_vcf through API or CLI

### ISSUE THREAD

**Issue by ghost** [sbslee/pypgx#76]
Dear sbslee,
When I try to use create_input_vcf function the program crashes with 'Segmentation fault'. I have tried the API in Python and just CLI, both with standard parameters and an own test bam and reference fasta. This also happens when calling this function in the GeT-RM WGS tutorial of your documentation. Is there a way to figure out what the actual underlying problem could be here? Many Thanks!

`>>> pypgx.api.utils.create_input_vcf(out_vcf, fasta, bams, assembly='GRCh37', genes=None, exclude=False, dir_path=None, max_depth=250)
Segmentation fault`

`$ pypgx create-input-vcf out.vcf.gz bwa06_1KGRef_PhiX/hs37d5_PhiX.fa blood_*_merged.mdup.bam
Segmentation fault`

`$ pypgx create-input-vcf grch37-variants.vcf.gz genome.fa grch37-bam/*.bam
Segmentation fault`

**Comment by sbslee** [comment]
@sebapir,

Thanks for the question. Can you show me the output of the command `$ conda list`? I need to see the list of packages installed in your conda environment and their versions.

I believe this issue is caused because you're currently using an outdated version of the `pysam` package. For details, please see this [bug report](https://github.com/pysam-developers/pysam/issues/928) I raised to the `pysam` developers. The latest version contains the fix for the issue. Therefore, please make sure you are using the latest version for each of the required packages.

**Comment by sbslee** [comment]
Please reopen it if the problem persists after reinstalling.

**Comment by ghost** [comment]
Updating pysam to the latest version worked. Thank you!
