### ISSUE TITLE
create-input-vcf error using numpy 1.24.1

### ISSUE THREAD

**Issue by michela-marcellino** [sbslee/pypgx#81]
Hi sbslee,

When I attempted to create an input vcf file, it would return 
> AttributeError: module 'numpy' has no attribute 'long'

I ended up installing numpy 1.23.0 (instead of the version 1.24.1 that I originally had), and that seemed to work. 
I just wanted to let you know.

Thank you!

**Comment by sbslee** [comment]
@michela-marcellino,

Thanks for reporting the issue and solution! I'm glad to hear that you were able to fix the problem on your own.

It sounds like the issue is related to the `fuc` package, which is one of the dependencies for PyPGx and is also a package developed by me. I've noticed that when people install PyPGx via `conda`, sometimes an old version of `fuc` ([link](https://github.com/sbslee/fuc)) is installed which can cause problems like the ones you observed. Therefore, next time you need to install PyPGx, I strongly recommend that you create a fresh conda environment with the latest versions of both `fuc` and `pypgx`:

```
$ conda create -n pypgx-env -c bioconda pypgx=0.20.0 fuc=0.36.0
```

Have fun with PyPGx!
