### ISSUE TITLE
Minor bug in pipeline.py all functions

### ISSUE THREAD

**Issue by anh151** [sbslee/pypgx#82]
If output exists and `force=False`, line 227 generates `FileExistsError`.

Could modify lines 224-227 to be:

```python
if os.path.exists(output):
    if force:
        shutil.rmtree(output)
        os.mkdir(output)
else:
    os.mkdir(output)
```

I gave `run_ngs_pipeline` as an example, but the same bug exists for other functions in the file as well.

**Comment by sbslee** [comment]
@anh151,

Thanks for opening the issue. I'm not 100% sure if I follow your logic. If `force=False` then it's supposed to throw an error like `FileExistsError` because there is no other option. The user clearly doesn't want to overwrite the existing output files, so he or she needs to change the output prefix. Would you please elaborate further?

**Comment by anh151** [comment]
If the directory exists because it contains other files that I want to keep together, then I wouldn't want to delete any existing files.  For example, in my case I am keeping the variants file and other ancillary data together with the outputs. In the current design, this option is not possible. But I do understand your example as well, I did not think of that.

I did modify the code on my end to the one above. I'll leave it up to you if you want to keep the code as is or modify it.

**Comment by sbslee** [comment]
@anh151,

I see what you mean. Yes, it was an intentional design. I'm trying to make things as simple as possible because many users of PyPGx are not necessarily proficient in programming. One possible issue with your approach is that a user might end up using an incorrect or corrupted file in the existing directory. Of course, advanced users like yourself wouldn't be exposed to this issue, but I'm sure you get what I mean.

That said, this is exactly the reason I provide PyPGx API because advanced users like yourself can easily incorporate and/or modify the API for specific purpose. For instance, if you just want to create a variant file for a specific gene, you can simply use the method [pypgx.utils.import_variants](https://pypgx.readthedocs.io/en/latest/api.html#pypgx.api.utils.import_variants) instead of running the entire pipeline.

Let me know if you need further help.
