### ISSUE TITLE
Is it possible to replace Depth of Coverage file with DP field?

### ISSUE THREAD

**Issue by seokho92** [sbslee/pypgx#84]
Hi, I am new to this field, and trying to grasp the genotyping and this wonderful pypgx.

I am currently working with vcf files, and generating depth of coverage with bam read is not possible for now.

I know my vcf files contain DP field, do you think it is reasonable to use this instead?

**Comment by sbslee** [comment]
@seokho92,

Great question! The short answer is no, PyPGx currently cannot detect structural variation directly from a VCF file, even if it contains the DP field. In order to accurately detect SV, you need a comprehensive profile of read depth across the gene of interest (e.g. CYP2D6). Therefore, having read depth only for a few loci in the case of VCF does not suffice.

That being said, do you have alignment files (i.e. BAM) for your VCF? If your VCF already has the DP field, it must have been created from NGS data. If you are interested in SV detection, I strongly recommend that you go back to BAM files and create a `CovFrame[DepthOfCoverage]` file properly.

Please let me know if you have further questions.

**Comment by seokho92** [comment]
Thanks so much for clearing this out!
