### ISSUE TITLE
CYP2D6 *4 calls

### ISSUE THREAD

**Issue by Pharmacogenetecist** [sbslee/pypgx#93]
Hello Steven, I had the following interesting call on *4 allele when comparing WGS to WES.

CPMUID	Gene	Genotype	Phenotype	Haplotype1	Haplotype2	AlternativePhase	VariantData	CNV
NA12878_WES	CYP2D6	*3/*68+*4	Poor Metabolizer	*3;*4;	*3;*4;*10;*74;	;	*3:22-42128241-CT-C:0.905;*4:22-42128945-C-T:0.878;*10:22-42130692-G-A,22-42126611-C-G:0.676,0.434;*74:22-42129819-G-T:0.391;	Tandem1A
NA12878_WGS	CYP2D6	*3/*68+*4	Poor Metabolizer	*3;	*3;*4;*10;*74;	;	*3:22-42128241-CT-C:0.867;*4:22-42128945-C-T:0.742;*10:22-42130692-G-A,22-42126611-C-G:0.607,0.391;*74:22-42129819-G-T:0.538;	Tandem1A

sample115_WES	CYP2D6	*4/*4	Poor Metabolizer	*4;*10;	*4;	;	*4:22-42128945-C-T:0.833;*10:22-42130692-G-A,22-42126611-C-G:0.474,0.487;	Normal
sample115_WGS	CYP2D6	*1/*4	Intermediate Metabolizer	*4;*10;	*1;	;	*4:22-42128945-C-T:0.712;*10:22-42130692-G-A,22-42126611-C-G:0.438,0.55;*1:default;	Normal

What is the PyPGX threshold for calling a HET VS HOM?

I have a few more interesting outputs comparing WGS to WES

Sample111_WES	CYP2D6	*14/*36+*10	Intermediate Metabolizer	*14;*2;	*10;	*114;*65;	*114:22-42129033-C-T,22-42130692-G-A:0.368,0.646;*10:22-42130692-G-A,22-42126611-C-G:0.646,0.975;*14:22-42129033-C-T:0.368;*65:22-42130692-G-A,22-42127941-G-A,22-42126611-C-G:0.646,0.299,0.975;*2:22-42127941-G-A,22-42126611-C-G:0.299,0.975;	Tandem2A
Sample111_WGS	CYP2D6	Indeterminate	Indeterminate	*10;	*14;*2;	*114;*65;	*114:22-42130692-G-A,22-42129033-C-T:0.631,0.273;*10:22-42130692-G-A,22-42126611-C-G:0.631,0.982;*14:22-42129033-C-T:0.273;*65:22-42130692-G-A,22-42127941-G-A,22-42126611-C-G:0.631,0.337,0.982;*2:22-42127941-G-A,22-42126611-C-G:0.337,0.982;	Tandem1A

Sample112_WES	CYP2D6	Indeterminate	Indeterminate	*1;	*29;*34;	;	*29:22-42129132-C-T,22-42127608-C-T:0.318,0.284;*34:22-42127941-G-A:0.295;*1:default;	Tandem2A
Sample112_WGS	CYP2D6	*1x2/*29	Ultrarapid Metabolizer	*1;	*29;*2;	;	*29:22-42129132-C-T,22-42127608-C-T:0.338,0.326;*2:22-42127941-G-A,22-42126611-C-G:0.314,0.203;*1:default;	WholeDup1

Sample122_WES	CYP2D6	*3/*9	Intermediate Metabolizer	*3;*35;	*9;	;	*3:22-42128241-CT-C:0.524;*9:22-42128173-CCTT-C:0.25;*35:22-42130761-C-T,22-42127941-G-A,22-42126611-C-G:0.465,0.495,0.497;	Normal
Sample122_WGS	CYP2D6	*9/*35	Normal Metabolizer	*35;	*9;	;	*9:22-42128173-CCTT-C:0.25;*35:22-42130761-C-T,22-42127941-G-A,22-42126611-C-G:0.482,0.581,0.409;	Normal

Likely a result of the Duplications or rearrangements causing havoc?

**Comment by Pharmacogenetecist** [comment]
The last one is actually a coverage issue, interesting, both WES and WGS for this sample had poor coverage in this region (due to the *9 deletion? possibly). However NA12878 - which also has the *3 deletion had great coverage.

See attached.
[Presentation1.pdf](https://github.com/sbslee/pypgx/files/11326810/Presentation1.pdf)

**Comment by sbslee** [comment]
@Pharmacogenetecist,

> What is the PyPGX threshold for calling a HET VS HOM?

PyPGx does not determine whether a given variant is HET or HOM. This is all done during the variant calling step (i.e. VCF). In other words, the variant caller you used (e.g. HaplotypeCaller) determines whether a variant is HET or HOM. PyPGx follows genotype calls that are shown in the input VCF.

For example, `sample115_WES` is `*4/*4` because the input VCF must have `22-42128945-C-T` as HOM (i.e. `1/1`). This can be seen by the high allelic depth of the variant (0.833 which is close to 1). On the contrary, `sample115_WGS` has `*1/*4` because the input VCF must have `22-42128945-C-T` as HET (i.e. `0/1`) with a decreased allelic depth of 0.712 (which is closer to 0.5).

> Likely a result of the Duplications or rearrangements causing havoc?

Could you show me the profiles of copy number and allele fraction from PyPGx? Images of read pileup are not too useful when it comes to SV detection.

**Comment by Pharmacogenetecist** [comment]
> @Pharmacogenetecist,
> 
PyPGx does not determine whether a given variant is HET or HOM. This is all done during the variant calling step (i.e. VCF). In other words, the variant caller you used (e.g. HaplotypeCaller) determines whether a variant is HET or HOM. PyPGx follows genotype calls that are shown in the input VCF.

: What about when one uses the create-input-vcf command, which caller is used?

> Could you show me the profiles of copy number and allele fraction from PyPGx? Images of read pileup are not too useful when it comes to SV detection.
Sure - attached.
[Presentation2.pdf](https://github.com/sbslee/pypgx/files/11337306/Presentation2.pdf)

**Comment by sbslee** [comment]
@Pharmacogenetecist,

Thanks for the additional information.

> What about when one uses the create-input-vcf command, which caller is used?

Under the hood, the `create-input-vcf` command uses `bctools` for variant calling. Please read the [FAQ](https://pypgx.readthedocs.io/en/latest/faq.html#variant-caller-choice) page for more details.

> Likely a result of the Duplications or rearrangements causing havoc?

In the case of `Sample122_WES` vs. `Sample122_WGS`, when you write "*9 deletion" and "*3 deletion" I will assume you are talking about indels, not gene deletion; `*3` is defined by `22-42128241-CT-C` while `*9` by `22-42128173-CCTT-C`. That being said, it appears `22-42128241-CT-C` was not captured well during WES library construction. I would advise you to check the input VCF and see the allelic ratio for this variant in `Sample122_WES` (even if the genotype call is `0/0`). However, this case was NOT caused by SV because the profiles look fine to me and in both cases the CNV call was `Normal`.

In the case of `Sample112_WES` vs. `Sample112_WGS`, it appears PyPGx correctly identified that there's SV but because copy number data was available in the coding regions only for WES, the final SV calls differed. There is not much to be done here because that's the limitation of using WES.

**Comment by Pharmacogenetecist** [comment]
> In the case of `Sample122_WES` vs. `Sample122_WGS`, when you write "*9 deletion" and "*3 deletion" I will assume you are talking about indels, not gene deletion; `*3` is defined by `22-42128241-CT-C` while `*9` by `22-42128173-CCTT-C`. That being said, it appears `22-42128241-CT-C` was not captured well during WES library construction. I would advise you to check the input VCF and see the allelic ratio for this variant in `Sample122_WES` (even if the genotype call is `0/0`). However, this case was NOT caused by SV because the profiles look fine to me and in both cases the CNV call was `Normal`.

Thanks Steven, yes I was referring to them as indels and not whole gene deletion. Unless I switched it around, 122 - actually WES called *3 and *9, but in WGS, only *9 was captured, and not *3 (due to low read depth at position 42128241 - only 6 reads). This region had strange coverage when looking at IGV over the 2D6/7 region, poorer than normal when compared to our other samples.

**Comment by sbslee** [comment]
@Pharmacogenetecist,

Oops, my bad on mixing those two up. Yes, the poor coverage could easily explain that away.

I'm still amazed by how well WES data was still able to call some of the SVs. The profiles look way better than I anticipated. Wouldn't recommend it for clinical, but definitely useful for research I'd assume. Anyways, thanks for sharing your data. Let me know if you need further help.
