### ISSUE TITLE
CYP2D6 *11 and *17

### ISSUE THREAD

**Issue by brettva** [sbslee/pypgx#94]
First I think it is amazing that you have wrestled a lot of the allele definitions together for PyPGx, but I have a question about  CYP2D6 *11 and *17

If I read right [PharmVar ](https://www.pharmvar.org/gene/CYP2D6) defines *11 as : `42126611C>G, 42127941G>A, 42129910C>G` (hg38)

In the `pypgx/api/data/allele-table.csv` it seems the hg38 core for CYP2D6 *11 is `22-42129910-C-G`

Similarly PharmVar defines CYP2D6 *17 as  `42126611C>G, 42127941G>A, 42129770G>A` (hg38)

In the `pypgx/api/data/allele-table.csv` it seems  the hg38 core for CYP2D6 *17 is `22-42129770-G-A`

Hopefully I am not misunderstanding, but just wondering if you have some insight on the difference. Thank you.

**Comment by sbslee** [comment]
@brettva,

Great question! The two star alleles you mentioned are defined by PharmVar as

- For `CYP2D6*11` (no function): `42126611C>G (S486T)`, `42127941G>A (R296C)`, `42129910C>G (splice defect)`
- For `CYP2D6*17` (decreased function): `42126611C>G (S486T)`, `42127941G>A (R296C)`, `42129770G>A (T107I)`

Now if you look at `CYP2D6*2` (normal function), it's defined as `42126611C>G (S486T)` and `42127941G>A (R296C)`.

What we can learn from above is the fact that the two variants `42126611C>G (S486T)` and `42127941G>A (R296C)`, which are shared between all three star alleles, do not affect enzymatic function of a given star allele. That's why PyPGx does not require those variants for calling `CYP2D6*11` and `CYP2D6*17`. Otherwise, if your sample whose true genotype is `CYP2D6*1/*17` for example happens to be genotyped as having only `42127941G>A (R296C)` and `42129770G>A (T107I)`, missing `42126611C>G (S486T)` due to a technical problem (e.g. low sequencing depth) or genotyping platform (e.g. NGS vs. SNP array), you would be calling an incorrect star allele for the sample.

That being said, the `allele-table.csv` file does provide two columns for storing variant data: `GRCh38Core` and `GRCh38Tag`. In the case of `CYP2D6*11`, `42129910C>G (splice defect)` is already listed as core variation. In theory, I should have put `42126611C>G (S486T)` and `42127941G>A (R296C)` as tag variation but I didn't have chance to go through all of the tag variants since they are not as important as core variation. When I created PyPGx I was hoping to get help from the community in this regard because the star allele database is growing and changing so rapidly.

Hope this helps!

**Comment by brettva** [comment]
@sbslee 

That makes a ton of sense. I have seen commercial tests that evaluate *11 as `42126611C>G, 42127941G>A, 42129910C>G`, but I am guessing that they scrutinize any missing data among these 3 variants as a part of the tests and are probably using an approach that has extremely high callrate anyways. 

I can understand the issue you describe when using imputed genotypes certainly and your strategy makes sense
