### ISSUE TITLE
CPIC level details

### ISSUE THREAD

**Issue by hongsheng-lai** [sbslee/pypgx#99]
First of all, I'd like to express my gratitude for your efforts with the pharmacogenetic tool. While conducting my research, I encountered some questions regarding the data and would like to seek clarification.

I wanted to inquire about the version of `pypgx/api/data/cpic-table.csv` you are using. When I checked the [official website](https://cpicpgx.org/genes-drugs/), I found that **ABCG2 is categorized as Level A**, whereas in your table, it is listed as **Level B**. Additionally, its status has been updated to "final" on the official website, but this change is not reflected in your table.

**Comment by sbslee** [comment]
@hongsheng-lai,

Thank you for the question! The file was last updated on Feb 6, 2022, so I'm not surprised there are some differences. PGx information (e.g. star alleles, phenotypes, recommendation, ...) evolves very rapidly and it's difficult to keep up with all the changes. I made PyPGx open source in the hope that it will become a community-driven project one day. That said, I'd be happy to update the CPIC table, unless you want to give it a try yourself, in which case I'd be more than happy to help. Please let me know.

**Comment by hongsheng-lai** [comment]
@sbslee ,
Thank you for your reply. I completely understand the challenges posed by the continuous updates of the database. Since I need to use multiple tools at once, I just want to ensure the accuracy of the data. In the future, I might attempt to establish a database update tool for mainstream open-source PGx tools (Aldy, Pharmcat, PyPGx ...). If there are further developments or any questions, I'll try to sync with you.

**Comment by sbslee** [comment]
@hongsheng-lai,

No worries. I updated the CPIC table in the `0.21.0-dev` branch. You can access it by:

```
$ git clone https://github.com/sbslee/pypgx
$ cd pypgx
$ git checkout 0.21.0-dev
$ pip install .
```

**Comment by brettva** [comment]
@sbslee thank you for developing this tool, we get a lot of use out of it. for my own record keeping I am wondering when the last time core variant definitions were updated? or did this update do that as well? Please let me know, thanks!

**Comment by sbslee** [comment]
@brettva,

That's a difficult question to answer because the core variant definitions evolve much faster and more broadly than the CPIC levels. Frankly speaking, the only way to find out would be to individually check the CHANGELOG document for each gene in PharmVar versus what PyPGx has. However, it's clearly not a straightforward task.

That being said, I'm actively seeking a better system to track all changes in variant definitions. Note that this challenge persists not only for PyPGx but for all PharmVar users since it's continually evolving.

P.S. This PR did not alter any variant data.
